# Prettier Configuration File

# https://prettier.io/docs/en/configuration.html
printWidth: 100
proseWrap: 'preserve'
singleQuote: true
semi: false

# per stylelint-config-twbs-bootstrap
overrides:
  - files: '*.scss'
    options:
      singleQuote: false
